concurrent: 30
check-interval: 300
timeout: 5000
min-speed: 800
download-timeout: 5
speed-test-url: https://github.com/VSCodium/vscodium/releases/download/1.98.0.25067/codium-1.98.0.25067-el9.aarch64.rpm
save-method: local
sub-urls:
  - https://raw.githubusercontent.com/mfuu/v2ray/master/clash.yaml
  - https://raw.githubusercontent.com/anaer/Sub/main/clash.yaml
  - https://cdn.jsdelivr.net/gh/vxiaov/free_proxies@main/clash/clash.provider.yaml
  - https://raw.githubusercontent.com/shaoyouvip/free/main/mihomo.yaml
mihomo-overwrite-url: https://raw.githubusercontent.com/shaoyouvip/free/main/mihomo.yaml
rename-node: true
media-check: false
keep-success-proxies: false
print-progress: false
sub-urls-retry: 3
subscheck-version: v2.2.8
gui-auto: false
success-limit: 0
