name: 定时 Subcheck 并更新 mihomo.yaml

on:
  schedule:
    # UTC 时间每天 0点、8点、16点（北京时间 8点、16点、0点）
    - cron: '0 0,8,16 * * *'
  workflow_dispatch: # 支持手动触发

jobs:
  speedtest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 仓库
      uses: actions/checkout@v3

    - name: 安装依赖
      run: |
        sudo apt-get update
        sudo apt-get install -y wget tar git

    - name: 下载 subs-check
      run: |
        wget https://github.com/chenlong13507664259/local/releases/download/sub-check-1.3.9/subs-check_Linux_x86_64.tar.gz
        tar -xzf subs-check_Linux_x86_64.tar.gz
        chmod +x subs-check

    - name: 运行 subs-check（超时 200 秒）
      run: |
        # 使用 timeout 确保 subs-check 不会无限阻塞
        timeout 200 ./subs-check -f config.yaml

    - name: 等待 mihomo.yaml 文件生成
      run: |
        echo "等待 mihomo.yaml 生成..."
        for i in {1..30}; do
          if [ -f local/output/mihomo.yaml ]; then
            echo "文件已生成"
            break
          fi
          sleep 1
        done

    - name: 查看生成文件（调试用）
      run: ls -R local/output

    - name: 提交更新到仓库
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

        # 复制到仓库根目录
        cp local/output/mihomo.yaml ./mihomo.yaml

        # 强制 add 和 commit（即使没变化也会更新）
        git add -f mihomo.yaml
        git commit -m "自动更新 mihomo.yaml" || echo "no changes"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
