name: Run subs-check internally

on:
  workflow_dispatch:       # 手动触发
  schedule:
    - cron: '0 6 * * *'   # 每天 6 点自动运行

jobs:
  run_subs_check:
    runs-on: windows-latest

    steps:
      # 1. Checkout 仓库
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. 确保 local 文件夹存在
      - name: Ensure local folder exists
        run: |
          New-Item -ItemType Directory -Force -Path .\local

      # 3. 下载 subs-check.exe（Release 里）
      - name: Download subs-check.exe from Release
        run: |
          Invoke-WebRequest -Uri "https://github.com/chenlong13507664259/local/releases/download/subs-check-1.0/subs-check.exe" -OutFile ".\local\subs-check.exe"

      # 4. 运行 subs-check 生成文件，保存在 local 文件夹
      - name: Run subs-check
        run: |
          .\local\subs-check.exe -f .\local\config.yaml

      # 5. 查看生成的文件（可选，调试用）
      - name: List generated files
        run: |
          dir .\local
