name: Update mihomo.yaml

on:
  workflow_dispatch:       # 手动触发
  schedule:
    - cron: '0 6 * * *'   # 每天 6 点自动运行

jobs:
  update_yaml:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download subs-check.exe from Release
        run: |
          Invoke-WebRequest -Uri "https://github.com/chenlong13507664259/local/releases/download/subs-check-1.0/subs-check.exe" -OutFile ".\local\subs-check.exe"

      - name: Run subs-check
        run: |
          .\local\subs-check.exe -f .\local\config.yaml

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Commit and push
        run: |
          git add mihomo.yaml
          git commit -m "Update mihomo.yaml [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
