name: Update mihomo.yaml

on:
  workflow_dispatch:       # 手动触发
  schedule:
    - cron: '0 6 * * *'   # 每天 6 点自动运行

jobs:
  update_yaml:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取仓库
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. 下载 Linux 可执行的 subs-check
      - name: Download subs-check
        run: |
          curl -L -o subs-check https://github.com/beck-8/subs-check/releases/latest/download/subs-check-linux
          chmod +x subs-check

      # 3. 执行生成 mihomo.yaml
      - name: Run subs-check
        run: |
          ./subs-check -f local/config.yaml

      # 4. 配置 git
      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      # 5. 提交并推送修改
      - name: Commit and push
        run: |
          git add mihomo.yaml
          git commit -m "Update mihomo.yaml [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
